name: CI Centos7

on: [pull_request]

jobs:
  test_apisix:
    name: run ci on centos7
    runs-on: ubuntu-latest

    steps:
    - name: Make rpm package
      run: |
        sudo gem install --no-document fpm
        # WOULD CHANGE TO MASTER WHEN PR GOT MERGED
        git clone https://github.com/idbeta/build-tools.git
        cd build-tools
        git checkout new-method-to-package
        # make package type=rpm app=apisix version=2.3 branch=2.3
        pwd
        ls


