name: CI

on: [pull_request]

jobs:
  test_apisix:
    name: run ci on centos7
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: export
      id: export
      run: |
        export A="abc"
        echo $A
        echo "##[set-output name=A;]$(echo "abcd")"

    - name: print
      run: |
        export A=${{ steps.export.outputs.A }}
        ./print.sh
