name: Actions

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.run_number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Actions
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: |
          echo ${{ github.ref }}
          echo ${{ github.run_number }}

      - name: Sleep
        run: |
          sleep 300
