name: CI

on: [pull_request]

jobs:
  test_apisix:
    name: run ci on centos7
    runs-on: ubuntu-latest
    env:
      A: "abcd"
    steps:
    - name: export
      run: |
        export A="abc"
        echo $A

    - name: print
      run: ./print.sh
